### ISSUE TITLE
Package??

### ISSUE THREAD

**Issue by jameshunterbr** [MangoTheCat/blog_worldcup2018#2]
In your blog text you have the command `devtools::load_all("worldcup")`. However, where is the package itself. You have the R program files and most of the data frames you need, but with rda files, we need to know how to open them and what to call the resulting object. Also, there is no params file, but the first commands after the devtools sets parameters in the params dataframe that I can't find. Please clarify your package structure and what order the commands and functions should be used.

**Comment by Avatoo** [comment]
If you go to the front page of this repo, you will see package `worldcup` as a subfolder of the root. Clone or download the repository, it will be inside. The main R Markdown notebook is `dataMod.Rmd`, which should be able to run after.

**Comment by Avatoo** [comment]
Closing issue then
