### ISSUE TITLE
Another Prediction for the FIFA World Cup 2018

### ISSUE THREAD

**Issue by davidfgeorge** [MangoTheCat/blog_worldcup2018#3]
I have downloaded the package, but it is not clear how to actually try the application? 
For example cannot see how to populate: 
normalgoals <- params$normalgoals ; nsim <- params$nsim

Thank you.

**Comment by Avatoo** [comment]
Hi there, to reproduce the code in the blogpost, please run through `dataMod.Rmd`. `params` is a field of R Markdown file and is declared in the header. Here is detailed introduction https://rmarkdown.rstudio.com/developer_parameterized_reports.html 

> Global parameters normalgoals (The average number of goals scored in a world cup match) and nsim (number of simulations) are declared in the YAML section at the top of the R Markdown document.

Hope that helps?

**Comment by davidfgeorge** [comment]
Hi. Many thanks. I will try that. Cheers.

David F. George
Want little, need less, give more
davidfgeorge@hotmail.com<mailto:davidfgeorge@hotmail.com>
uk.linkedin.com/in/dfgeorge
Mobile: +44 7468 858638
